Add dz10
Kukrynitza/lessons pull request #10
Opened 2024-10-01 19:02 UTC by Kukrynitza

2024-10-06 16:06 UTC, vladshcherbin requested changes
добавь eslint и примени все правки, которые сделаешь в 11-ом

2024-10-07 19:57 UTC, vladshcherbin requested changes
Парочка правок, проверь eslint-ом. Вроде вся конфиграция есть, а форматирование неверное

забыл выполнить `npm install`?

2024-10-07 19:57 UTC, vladshcherbin commented on dz10/app.js
> +function availabilityInStock(quantity){
начинай название функций с глагола

2024-10-07 19:57 UTC, vladshcherbin commented on dz10/app.js
> +function ConsoleLog(name, price){
начинай название функций с нижнего регистра и задай название соответствующее тому, что она делает

2024-10-07 19:57 UTC, vladshcherbin commented on dz10/app.js
> +  const string =`${name} стоит(-ят) ${price} рублей`
переменная не нужна, если только в качестве практики использовал)

2024-10-07 19:57 UTC, vladshcherbin commented on dz10/.eslintrc.cjs
файл содержит ошибки `eslint`

2024-10-07 19:57 UTC, vladshcherbin commented on dz10/app.js
файл содержит ошибки `eslint`

2024-10-09 18:12 UTC, vladshcherbin requested changes
Все те же правки и остались

- проверить файлы eslint-ом
- поменять названия функций так, чтобы было понятно, что они делают
- начинать название функции с глагола

2024-10-14 10:55 UTC, vladshcherbin requested changes
правки всё те же

2024-10-14 10:55 UTC, vladshcherbin commented on dz10/.eslintrc.cjs
в файле есть ошибки eslint

2024-10-14 10:55 UTC, vladshcherbin commented on dz10/src/app.js
> +function inStock(quantity) {
название функции должно отражать то, что она делает, и начинаться с глагола

2024-10-14 10:55 UTC, vladshcherbin commented on dz10/src/app.js
> +function consoleLog(name, price) {
название функции должно отражать то, что она делает, и начинаться с глагола

2024-10-15 10:57 UTC, vladshcherbin requested changes
поправил конфиг `.eslintrc.cjs`

названия хорошие - лучше тех, что были 😅👍

2024-10-15 10:57 UTC, vladshcherbin commented on dz10/.eslintrc.cjs
> +}
```suggestion
module.exports = {
  extends: '@shcherbin/eslint-config-node',
  rules: {
    'no-console': 'off'
  }
}

```

- добавил правильно чтобы не ругалось на console.log
- добавил пустую строку в конце файла - в этом и была ошибка eslint

2024-10-16 15:31 UTC, Kukrynitza commented on dz10/.eslintrc.cjs
> +}
Наверное это относилось к дз12), я её слил до того как заметил

2024-10-16 17:42 UTC, vladshcherbin approved these changes

2024-10-17 19:09 UTC, merged