Add dz19
Kukrynitza/lessons pull request #19
Opened 2024-11-02 16:47 UTC by Kukrynitza

2024-11-02 19:12 UTC, vladshcherbin requested changes
в целом очень хорошо, пара правок на запомнить

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/index.html
> +</body>
внутри всегда должен быть `div`, в который приложение рендерится

на случай если у тебя несколько скриптов рендерят, каждый в свой элемент

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/index.html
> +  <title>Document</title>
title под meta, название не соответствует содержимому

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/index.html
> +<html lang="en">
язык неверный

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/package.json
> +}
я бы форматировал очерёдность полей как в примере (самое важное, что нужно видеть, повыше), но это уже вкусовщина - на твоё усмотрение

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/src/app.css
> +  font-family: "Lucida Sans", "Lucida Sans Regular", "Lucida Grande", "Lucida Sans Unicode", Geneva, Verdana, sans-serif;
шрифты прописаны, но не подключены - не у всех они есть

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/src/components/Footer/App.jsx
неверное название компонента (App.jsx)

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/src/components/Header/App.jsx
неверное название файла - файлы должны называться соответствующе названию компонента (в этом случае Header.jsx). с файлами стилей тоже самое

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/src/components/Header/App.jsx
> +          <li ><a href="home">Главная</a></li>
```suggestion
          <li><a href="/">Главная</a></li>
```

ссылки обычно начинаются с `/` (корень сайта)

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/src/components/Header/App.jsx
> +          <li><a href="blog">Блог</a></li>
```suggestion
          <li><a href="/blog">Блог</a></li>
```

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/src/components/Header/App.jsx
> +          <li><a href="contact">Контакты</a></li>
```suggestion
          <li><a href="/contact">Контакты</a></li>
```

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/src/components/Main/App.jsx
> +              контента.
не переноси, сделай в одну строчку и позволь редактору и браузеру переносить текст)

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/src/components/Main/App.jsx
> +            <p className={styles.date}>13 февраля 2023</p>
этот элемент трижды дублируется, создай массив объектов снаружи и выведи их используя `.map` и разметку один раз (как в примере урока список)

таким образом, если вдруг что-то добавится или поменяется в разметке - поменять нужно будет в 1 месте, а не в каждом элементе

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/src/index.jsx
> +  </>
создай отдельный компонент App.jsx (корневой) с этими элементами - иногда его импортируют ещё куда-то, поэтому и создают отдельный компонент

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/src/index.jsx
> +import './reset.css'
эти стили дублируются в `index.html` - оттуда можно удалить. но помнить, что `reset` должен быть до всех других стилей (`app`)

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/stylelint.config.js
в файле есть ошибки eslint

2024-11-02 19:12 UTC, vladshcherbin commented on dz19/vite.config.js
в файле есть ошибки eslint

2024-11-02 19:57 UTC, Kukrynitza commented on dz19/index.html
> +</body>
Мой новый вариант хороший?

2024-11-02 20:00 UTC, Kukrynitza commented on dz19/src/components/Main/App.jsx
> +            <p className={styles.date}>13 февраля 2023</p>
А вообще, для такого создается отдельный файл с данными?

2024-11-02 20:22 UTC, vladshcherbin commented on dz19/index.html
> +</body>
@Kukrynitza нового варианта не вижу

2024-11-02 20:24 UTC, vladshcherbin commented on dz19/src/components/Main/App.jsx
> +            <p className={styles.date}>13 февраля 2023</p>
@Kukrynitza зависит от компонента, если добавляются всякие обработчики событий - то да. в конкретно этом случае компонент простенький, выводит карточку - можно и не создавать

во вторник рассмотрим, как выносить в отдельный и прокидывать параметры (в этом задании не нужно)

2024-11-03 13:44 UTC, Kukrynitza commented on dz19/index.html
> +</body>
Есть, он был позже...

2024-11-04 11:27 UTC, vladshcherbin requested changes
вторая тележка правок 🙌

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/eslint.config.js
в файлике есть ошибки eslint

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/eslint.config.js
> +      'no-console': 'off'
в консоль мы ничего не выводим - правило не используется и отключать не нужно

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/index.html
> +  <link rel="stylesheet" href="src/app.css">
эти 2 файлика не нужны т.к. мы их напрямую импортируем в index.jsx - vite при сборке их объединит и сохранит в css файлик

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/src/App.jsx
> +export default function Body() {
```suggestion
export default function App() {
```

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/src/App.jsx
> +      </header>
не нужно так делать - верни `<header>` в `<Header>`

Пускай в компоненте будет весь компонент, а не только его содержимое

Если понадобится стили для `<header>` добавить, ты ведь не будешь их задавать в `App.module.css`

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/src/App.jsx
> +      </footer>
аналогично для этих

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/src/components/Header/Header.jsx
> +        <li ><a href="/home">Главная</a></li>
```suggestion
        <li><a href="/home">Главная</a></li>
```

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/src/components/Main/Main.jsx
> +const courses = [
хорошо, теперь можешь вынести эту переменную в отдельный файл как дефолтный экспорт и сюда её импортировать чтобы файл был чистенький и все данные были в одном месте

например в `src/data/courses.js`

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/src/index.jsx
> +import Body from './App.jsx'
```suggestion
import App from './App.jsx'
```

для дефолтный импортов используй названия соответствующе названию файлов - это упрощает понимание где и что, когда импортов и файлов в проекте много

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/src/index.jsx
> +const root = createRoot(document.querySelector('body'))
для селектора используй всегда какой-то `div` вместо `body` (во вторник покажу зачем)

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/stylelint.config.js
в файлике есть ошибки eslint

2024-11-04 11:27 UTC, vladshcherbin commented on dz19/vite.config.js
в файлике есть ошибки eslint

2024-11-25 15:50 UTC, vladshcherbin approved these changes
Вынес курсы в отдельную папку (вдруг ещё бы где-то пригодились), исправил глобальные стили

2024-11-26 07:37 UTC, merged